### ISSUE TITLE
Code only works with same pair

### ISSUE THREAD

**Issue by dookiethedog** [emilamaj/Articles-mev-bot-series#1]
I notice a lot of arbitrage done out there is done with triangular arbitrage or even more length. Do you plan to update this in future to include the math for optimal trade amount for any x length of arbitrage path? Also I noticed this focuses on univ2, any chance of v3 as well? or even including potentially both v2 and v3 pairs in the same arb path?

**Comment by emilamaj** [comment]
Yes, absolutely.
An efficient way to handle arbitrary-length arbitrage paths will be presented in one of the following articles, as well as a detailed explanation of how v3 performs swaps (the code will of course also be presented)
The only question is when, as I'm struggling right now to find time to write the articles. Stay tuned
